project:
  type: website
jupyter: julia-1.10  
execute:
  freeze: auto
date: last-modified  
margin-header: "⚠️ *Place holder for future documentation site for [CitableCorpus.jl](https://cite-architecture.github.io/CitableCorpus.jl/stable/).*"
format:
  html: 
    toc: true


website:
  title: "citablecorpus"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Tutorials"
        file: tutorials/index.qmd    
      - text: "Concepts"
        file: concepts/index.qmd           
      - text: "Guides"
        file: guides/index.qmd           
      - text: "Reference"
        file: reference/index.qmd  
    right:   
      - icon: github
        href: https://github.com/cite-architecture/CitableText.jl
        aria-label: GitHub

  sidebar:
    - title: "Tutorials"
      contents: 
        - tutorials/index.qmd

    - title: "Guides"
      contents:
        - guides/index.qmd

    - title: "Reference"
      contents: 
        - reference/index.qmd

    - title: "Concepts"
      contents: 
        - concepts/index.qmd

        

    - title: "Home"
      contents:
        - index.qmd               
 

