---
title: "Citable text corpora"
---


The CitableCorpus.jl package defines functions for working with the following structures:

- a `CatalogedText` text associates labelling metadata with an identifying URN for a concrete version of a text.
- a `TextCatalogCollection` is a collection of `CatalogedText`s.
- a `CitablePassage` represents a passage of text.  It associates a `CtsUrn` with a string value for the content of the passage.
- a `CitableTextCorpus` contains an ordered list of `CitablePassages` belonging to one or more versions of one or more texts.



## Contents


| | Learning the package | Using the package |
| --- | --- | --- |
| **Hands-on** |  Try a [tutorial](./tutorials/) to start using  the package  | Find [recipes](./guides/) for specific tasks |
| **Cognition** | Learn [concepts](./concepts/)   | See [reference information](./reference/) (including API documentation for all exported functions) |


## Status


::: {.callout-note title="In development"}

A future release of `CitableCorpus` is planned to add `CitableDocument` and `CitableDocumentCollection` types. 

The `CitableDocument` represents a single cataloged document. It associates an ordered list of `CitablePassages`, all belonging to a single version of a single text, with a `CatalogedText`.  The `CitableDocumentCollection` is list of `CitableDocument`s.
:::